// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5TKdHQT8xk48--c4lphZXVwPTH9W_LEM',
    appId: '1:926807285182:android:0d28f1301043d53615adef',
    messagingSenderId: '926807285182',
    projectId: 'plant-care-969e6',
    storageBucket: 'plant-care-969e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEg0ixjmXvDJHGAosGM224VJjwS5ekU60',
    appId: '1:926807285182:ios:8481caa0bc20388415adef',
    messagingSenderId: '926807285182',
    projectId: 'plant-care-969e6',
    storageBucket: 'plant-care-969e6.firebasestorage.app',
    iosBundleId: 'com.example.plantCare',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPeBTDDk1Rq_q334fr8Omcz4t8M14nw8o',
    appId: '1:926807285182:web:3908ea8088ef47fe15adef',
    messagingSenderId: '926807285182',
    projectId: 'plant-care-969e6',
    authDomain: 'plant-care-969e6.firebaseapp.com',
    storageBucket: 'plant-care-969e6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEg0ixjmXvDJHGAosGM224VJjwS5ekU60',
    appId: '1:926807285182:ios:8481caa0bc20388415adef',
    messagingSenderId: '926807285182',
    projectId: 'plant-care-969e6',
    storageBucket: 'plant-care-969e6.firebasestorage.app',
    iosBundleId: 'com.example.plantCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPeBTDDk1Rq_q334fr8Omcz4t8M14nw8o',
    appId: '1:926807285182:web:6921c8630eae37f615adef',
    messagingSenderId: '926807285182',
    projectId: 'plant-care-969e6',
    authDomain: 'plant-care-969e6.firebaseapp.com',
    storageBucket: 'plant-care-969e6.firebasestorage.app',
  );

}